# Generated by Django 2.1.5 on 2019-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='visible',
            field=models.CharField(max_length=1),
        ),
    ]
