# Generated by Django 2.1.5 on 2019-01-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_auto_20190122_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
