# Generated by Django 2.1.5 on 2019-01-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_auto_20190122_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
    ]
