# Generated by Django 2.1.5 on 2019-02-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_remove_menuitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='visible',
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='Enter menu name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
